version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  VK_SDK_PATH: C:\VulkanSDK
install:
- ps: >-
    git submodule --quiet update --init

    Start-FileDownload https://vulkan.lunarg.com/sdk/download/1.0.65.0/windows/VulkanSDK-1.0.65.0-Installer.exe -FileName VulkanSDK.exe

    .\VulkanSDK.exe /S /D=C:\VulkanSDK
build_script:
- ps: msbuild /t:Restore,Build /p:Configuration=Release /m /v:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test: off
artifacts:
- path: x64\Release\VulkanRenderer.exe
  name: VulkanRenderer